export const SET_USUARIO = 'SET_USUARIO';
export const REMOVE_CATEGORY = 'REMOVE_CATEGORY';
export const SET_USUARIO_LOGIN = 'SET_USUARIO_LOGIN';
export const SYNC_CATEGORY = 'SYNC_CATEGORY';
export const SYNC_CATEGORY_BY_WALLET = 'SYNC_CATEGORY_BY_WALLET';
export const INSERT_CATEGORY = 'INSERT_CATEGORY';

